using System;
using System.Collections.Generic;

#nullable disable

namespace Repository.Models
{
    public partial class ResolvedTicket
    {
        ///<summary>
        ///Model for admin report tickets for Entity Framework.
        ///Autogenerated by EntityFramework.
        ///</summary>
        public int TicketId { get; set; }
        public string ItemId { get; set; }
        public string AffectedService { get; set; }
        public string Descript { get; set; }
        public DateTime? TimeSubmitted { get; set; }
    }
}
